import Image from "next/image";
import { Button } from "../components/ui/button";
import Hero from "@/views/Hero";
import ProductsLists from "@/views/ProductsLists";

export default function Home() {
  return (
    <>
      <header />
      <Hero />
      <ProductsLists />
      {/* Lorem ipsum dolor sit amet consectetur adipisicing elit. A enim veniam aliquid delectus accusantium asperiores consequuntur voluptatum. Dicta quod, debitis et quis corporis, necessitatibus natus obcaecati quam quidem, nesciunt explicabo veritatis iure. Animi iste eligendi, voluptatibus natus rerum corrupti laboriosam magni excepturi iusto non, laborum, modi aperiam vel blanditiis eaque quas nulla totam ducimus. Consectetur aspernatur placeat, magni tenetur soluta perspiciatis unde illum corporis odio veritatis quae totam repudiandae quis ratione rem illo excepturi, ex nemo eveniet blanditiis ab. Fugit dolores fugiat soluta dignissimos voluptatibus, laudantium sequi suscipit quos repellat veritatis assumenda saepe culpa voluptatem beatae illum corporis debitis repudiandae. */}
      {/* Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis aspernatur provident, dolores, praesentium rerum ut sequi id odit excepturi ipsum quo maxime animi quae harum perferendis. Sed sapiente quisquam consequatur doloremque autem nihil tempore nostrum in aliquid distinctio officia, pariatur, et, ipsa totam? Dolorem doloribus rem modi laborum nulla quam ullam vero nesciunt maiores alias nemo itaque eos dolor quas nostrum optio vel dicta, architecto in earum voluptatum sequi minima cum odit. Debitis, provident itaque eos vero assumenda, possimus, enim fugiat quos incidunt dignissimos labore nemo! Ea provident enim reprehenderit sint quas aliquid accusamus architecto voluptas earum, distinctio dolores laudantium dignissimos culpa rerum tenetur delectus saepe inventore sit sequi nisi? Quod modi ullam tenetur natus adipisci eius exercitationem, consectetur voluptates, rem iusto ipsum neque unde voluptatem. Odit ab dignissimos explicabo debitis natus corporis, excepturi ducimus incidunt. Minus culpa recusandae fugiat excepturi accusamus ut inventore molestiae necessitatibus ipsum, architecto dolorem quibusdam! */}
      {/* Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda nesciunt aliquid amet facilis, eligendi numquam dolorum in quia eos ratione aliquam veritatis ducimus quos iure velit natus repellendus et quaerat provident fugiat pariatur! Hic accusantium minima, molestias iste, laboriosam est obcaecati consectetur ea eligendi vero animi, nobis quos mollitia architecto dolorem sint perspiciatis vel beatae distinctio. Rem vel dolores beatae harum illo ullam corrupti itaque. Minima, nisi fugit nobis delectus iure, esse quibusdam quam ad vero necessitatibus at voluptatum excepturi eaque eos impedit illo perferendis magnam vitae consequuntur itaque earum, beatae dolores assumenda. Corrupti est ipsa totam laboriosam blanditiis recusandae vitae, quas earum omnis eum dicta tempore quod dolor, perspiciatis, voluptatem libero provident debitis. Est veniam animi quo molestiae. Assumenda perspiciatis officiis aperiam nam dolorem veniam corrupti eaque quia incidunt vero nulla suscipit aliquam, architecto voluptatibus voluptatem expedita. Odit sit ipsam pariatur labore nihil id libero similique hic quos doloremque odio in, adipisci velit. Voluptatum delectus accusantium amet eos facilis, minus aliquam repudiandae ipsam similique fugiat excepturi sed nesciunt voluptas nam optio incidunt, cumque atque beatae repellendus. Excepturi omnis eum quas blanditiis? Corrupti quaerat rerum quibusdam totam. Autem incidunt voluptatibus veritatis. Eligendi perferendis iste dolores cumque nemo accusantium eius explicabo! */}
      {/* Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem maiores explicabo numquam. Dolores, aperiam quia. Quos exercitationem praesentium odio soluta inventore, labore, aliquid sint impedit et eveniet quo, quam at minus. Beatae atque molestias neque odit cum, voluptates provident eius dolorum nobis, fugit cupiditate rem deserunt quo doloribus explicabo architecto blanditiis nostrum? Assumenda dolorem quisquam veritatis porro molestias temporibus hic ut, voluptate voluptates impedit accusamus et, sequi asperiores necessitatibus maxime ea maiores incidunt tempore beatae voluptatum sunt! Molestiae adipisci maxime asperiores dolores maiores reiciendis ipsam sint enim exercitationem corporis delectus totam a mollitia facere quas repellendus tempore ab, illum officia. */}
      {/* Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque, repellendus? Aperiam cum voluptatum, dicta architecto veritatis ducimus sit dolorem quasi, doloribus, natus deserunt molestiae mollitia dolores perspiciatis id impedit cumque illum saepe aspernatur culpa esse. Eveniet ducimus, inventore earum facilis vitae, eaque, dolor fugiat labore iusto porro quae ab deleniti? */}
      {/* Lorem ipsum dolor sit amet consectetur adipisicing elit. Error ut accusamus quos maiores voluptatibus perspiciatis asperiores eaque voluptates hic consequatur. */}
      {/* Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum repudiandae ipsa tempore accusantium, voluptatem est dolore culpa. Ipsum, libero atque exercitationem repellat minus hic voluptatem cupiditate ullam blanditiis rem incidunt sapiente nihil quae excepturi, molestiae architecto quaerat provident earum a? */}
      {/* Lorem ipsum dolor sit amet. */}
    </>
  );
}
